Upgraded the script and meta file issues in the current package.
XRTK/WebXR pull request #9
Opened 2021-04-19 18:07 UTC by SimonDarksideJ

# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Resolved the upgrade issues with the recent Core update, including the HandProfile update for Grip strength.

The Hand profile might need regenerating with the new Grip Strength parameter.  Also, the platform configuration profile needs adding 
(see - https://github.com/XRTK/Oculus/blob/development/XRTK.Oculus/Packages/com.xrtk.oculus/Profiles~/OculusPlatformServiceConfigurationsProfile.asset)
Couldn't in my version due to a local issue.

2021-04-19 18:12 UTC, StephenHodgson submitted a review, later dismissed

2021-04-20 03:41 UTC, StephenHodgson requested changes
Compiler errors

2021-04-22 14:29 UTC, SimonDarksideJ commented
Ok, looking in to this error
> The type or namespace name 'Editor' does not exist in the namespace 'XRTK.Utilities'

The others are due to the SimpleWebXR dependency, which will only be resolved once its repackaged

2021-04-22 16:05 UTC, SimonDarksideJ commented
Ok, the WebXR component is fixed and should be able to force merge.  But until the Submodule updates to a clean UPM package, that part won't build @StephenHodgson @Rufus31415

2021-04-22 16:55 UTC, SimonDarksideJ commented
This is frustrating, I built the project and had fixed the things the errors it's reporting.  Ok, double checking

2021-04-22 23:43 UTC, SimonDarksideJ commented
Yay, Build passed. The COre dependancy was the last wrinkle.  

Ok to merge now @StephenHodgson  / @Rufus31415

2021-04-23 01:17 UTC, StephenHodgson commented on XRTK.WebXR/Packages/manifest.json
> +    "com.xrtk.core": "0.2.9",
I think this is up to 0.2.10

2021-04-23 01:17 UTC, StephenHodgson commented on XRTK.WebXR/Packages/com.xrtk.webxr/package.json
> +  "version": "0.2.2",
We've never actually made a release for this. It should be 0.2.0

2021-04-23 01:18 UTC, StephenHodgson requested changes
See comments

2021-04-27 16:19 UTC, merged